export const toDos = [
  {
    userId: 1,
    id: 1,
    title: "delectus aut autem",
    removed: false,
    completed: false,
  },
  {
    userId: 1,
    id: 2,
    title: "quis ut nam facilis et officia qui",
    removed: false,
    completed: false,
  },
  {
    userId: 1,
    id: 3,
    title: "fugiat veniam minus",
    removed: false,
    completed: false,
  },
  {
    userId: 1,
    id: 4,
    title: "et porro tempora",
    removed: false,
    completed: false,
  },
  {
    userId: 1,
    id: 5,
    title: "laboriosam mollitia et enim quasi adipisci quia provident illum",
    removed: false,
    completed: false,
  },
  {
    userId: 1,
    id: 6,
    title: "qui ullam ratione quibusdam voluptatem quia omnis",
    removed: false,
    completed: false,
  },
  {
    userId: 1,
    id: 7,
    title: "illo expedita consequatur quia in",
    removed: false,
    completed: false,
  },
  {
    userId: 1,
    id: 8,
    title: "quo adipisci enim quam ut ab",
    removed: false,
    completed: false,
  },
  {
    userId: 1,
    id: 9,
    title: "molestiae perspiciatis ipsa",
    removed: false,
    completed: false,
  },
  {
    userId: 1,
    id: 10,
    title: "illo est ratione doloremque quia maiores aut",
    removed: false,
    completed: false,
  },
  {
    userId: 1,
    id: 11,
    title: "vero rerum temporibus dolor",
    removed: false,
    completed: false,
  },
  {
    userId: 1,
    id: 12,
    title: "ipsa repellendus fugit nisi",
    removed: false,
    completed: false,
  },
];
export default toDos;
